# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started

baseURL = "https://calebxb.com/"
theme = "academic"
#themesDir = "themes"
defaultContentLanguage = "en"

title = "Caleb Bugg"

[author]
  name = "Caleb Bugg"

[pagination]
  pagerSize = 15

[outputs]
  home = ["html", "rss", "json"]
  page = ["html"]
  section = ["html", "rss"]
  taxonomy = ["html", "rss"]
  term = ["html", "rss"]

[params.author]
  name = "Caleb Bugg"
  bio = "Caleb is a researcher focused on stochastic optimization, large-scale models, and policy recommendations."
  image = "images/author.jpg"

  [params.header]
    logo = "Home"

  [params.homepage]
    layout = "page"
    showRecent = true

[params.article]
  showAuthor = true
  showBreadcrumbs = true
  showDate = false
  showReadingTime = true

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
