languageCode = "en-AU"
languageName = "English (Australia)"
languageDirection = "ltr"
weight = 1

title = "Caleb Bugg"
copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "Caleb Bugg"
  image = "img/author.jpg"
  headline = "Feed the People"
  bio = "JOSHUA GROUP: Analytics for All"
  links = [
    { email = "mailto:cbugg@breastfeedingrose.org" },
    { linkedin = "https://www.linkedin.com/in/caleb-xavier-bugg-4a703161/" }
  ]
